services:
  pocket_cart:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:dev
    env_file:
      - ./.env
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/usr/src/app
  postgres:
    image: postgres:15-alpine
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
volumes:
  pgdata:
networks:
  internal:
    driver: bridge
  common:
    external: true
