INSERT INTO products (product_name)
VALUES
    ('Bread'),
    ('Milk'),
    ('Eggs'),
    ('Cheese'),
    ('Bananas'),
    ('Apples'),
    ('Chicken'),
    ('Rice'),
    ('Potatoes'),
    ('Carrots'),
    ('Tomatoes'),
    ('Onions'),
    ('Lettuce'),
    ('Oranges'),
    ('Cereal'),
    ('Butter'),
    ('Yogurt'),
    ('Frozen vegetables'),
    ('Pasta'),
    ('Canned beans'),
    ('Olive oil'),
    ('Sugar'),
    ('Flour'),
    ('Salt'),
    ('Garlic'),
    ('Beef'),
    ('Pork'),
    ('Frozen pizza'),
    ('Fruit juice'),
    ('Coffee'),
    ('Tea'),
    ('Toilet paper'),
    ('Paper towels'),
    ('Dish soap'),
    ('Shampoo'),
    ('Toothpaste'),
    ('Canned tomatoes'),
    ('Canned tuna'),
    ('Peanut butter'),
    ('Jelly'),
    ('Crackers'),
    ('Snacks'),
    ('Chips'),
    ('Chocolate'),
    ('Ice cream'),
    ('Frozen meals'),
    ('Soft drinks'),
    ('Water'),
    ('Wine'),
    ('Beer'),
    ('Cleaning supplies')
